### ISSUE TITLE
RandomSplitter : TypeError: Can't instantiate abstract class WheatParser with abstract methods bboxes, labels

### ISSUE THREAD

**Issue by rashmimarganiatgithub** [lgvaz/mantisshrimp#214] opened 2020-07-24 16:01 UTC
Hi Aditya,

 RandomSplitter is not able to split the train and validation dataset properly from WheatParser. Could you please correct the format ( def filepath(self, o) -> Union[str, Path]:
        return self.source / f"{o.image_id}.jpg"
) code from WheatParser class from https://www.kaggle.com/okeaditya/fastaiv2-pytorch-lightning-fasterrcnn

**Comment by oke-aditya** [comment] 2020-07-24 16:02
I am Looking into it. cc @lgvaz

**Comment by oke-aditya** [comment] 2020-07-24 16:08
I am able to replicate the issue. @lgvaz this was working previously. What is the recent change that we need to adopt ?
Below is the error when running
```
parser = WheatParser(df, source / "train")
```
RandomSplitter is working fine.
```
TypeError: Can't instantiate abstract class WheatParser with abstract methods bboxes, labels
```
Thanks @rashmimarganiatgithub for the bug !!!

**Comment by oke-aditya** [comment] 2020-07-24 16:14
This tutorial is gone way off track. The reason is so much change in the API and our codebase.  We would need some changes to make it run https://www.kaggle.com/okeaditya/fastaiv2-pytorch-lightning-fasterrcnn

It might take a while to revamp the kernel to make it work, We need some changes in the model too.
But the wheat parser will be fixed soon.

**Comment by oke-aditya** [comment] 2020-07-24 16:19
I have fixed the parser issue @rashmimarganiatgithub . The model might not work coz of a recent update.

**Comment by lgvaz** [comment] 2020-07-24 17:00
The modifications to make it work with the new model API are very simple, can you work on that @oke-aditya ?

Also, you can now use `COCOMetric` =)

**Comment by oke-aditya** [comment] 2020-07-24 17:01
Yep. I will fix it up by tomorrow 😀 I was more concerned about parser. But that seems good.

**Comment by rashmimarganiatgithub** [comment] 2020-07-25 09:52
Thanks @lgvaz and @oke-aditya  for a quick look, waiting for a fix and uprunning kernel to use this library. Please keep me posted only 10 days left to try out your library. Please make it as soon as possible.

**Comment by oke-aditya** [comment] 2020-07-25 09:55
@lgvaz looks like that contest is gonna end. I will fix it up and create one for efficient det as well. 😀 @rashmimarganiatgithub I am fixing it. I will tag you on Kaggle once I create a new version. It will be up before today 👍

**Comment by rashmimarganiatgithub** [comment] 2020-07-25 10:51
@oke-aditya thanks for the quick response. Will it support for all range of efficientnetB0-B7?

**Comment by oke-aditya** [comment] 2020-07-25 11:10
Yes We use ross wightman's implementation of efficient Det. https://github.com/rwightman/efficientdet-pytorch
It supports a variety of backbones. Including all efficient net B0-b7. Also pre trained weights on COCO are available are for some.
I have tried in mantisshrimp once. Max I could train was b4 on Kaggle.

**Comment by oke-aditya** [comment] 2020-07-25 13:03
Hey, @rashmimarganiatgithub I have fixed up the notebook and Trained a faster rcnn resnet 152 FPN network too. It might help you to get a good score on LB. FRCNN is really good with Resnet 152 FPN. I have tested this and it works. I am attaching notebook here as well in case it doesn't show up in Kaggle. I have updated on Kaggle as well (if it doesn't show up do let me know) Happy Building. Below is a zip with ipynb code.

[Fastaiv2+PyTorch Lightning FasterRCNN.zip](https://github.com/lgvaz/mantisshrimp/files/4975530/Fastaiv2%2BPyTorch.Lightning.FasterRCNN.zip)

With mantis, you can train on Multiple gpus too. So do try that to win up the competition and best luck 👍

**Comment by oke-aditya** [comment] 2020-07-25 14:17
I guess we can add that above notebook as advanced guide.

**Comment by rashmimarganiatgithub** [comment] 2020-07-25 15:57
@oke-aditya thanks much. I will now use it for other competition too. Hence I need to understand Randomsplitter. Could you please point me to the codebase.

**Comment by rashmimarganiatgithub** [comment] 2020-07-25 15:57
@oke-aditya  thanks for the help

**Comment by oke-aditya** [comment] 2020-07-25 16:07
[Here ](https://github.com/lgvaz/mantisshrimp/blob/master/mantisshrimp/parsers/splits.py)is the source code for Randomsplitter. Also all the code is in the mantisshrimp [folder ](https://github.com/lgvaz/mantisshrimp/blob/master/mantisshrimp/).

Feel free to use it and do let us know whenever you build something great / new with this. Just open an Issue for it. Or post in #125 .

**Comment by rashmimarganiatgithub** [comment] 2020-07-25 16:15
@oke-aditya, Sure, I will keep you posted on the same.

**Comment by rashmimarganiatgithub** [comment] 2020-07-25 16:16
@lgvaz @oke-aditya. Closing this issue. thanks for your good work.

**Comment by rashmimarganiatgithub** [comment] 2020-07-26 11:23
@oke-aditya , can you please provide me mantisshrimp git repro code with .whl file. installing a package using online in contest is prohibited. Can you please make it quick.

**Comment by oke-aditya** [comment] 2020-07-26 11:38
Ok so I get the problem. I guess in the competition like Kaggle internet is disabled for submission. For that, you won't be able to install mantisshrimp from github. 

Since this is built on PyTorch you don't need the entire repo. I Suggest you train a model with mantisshrimp in a training kernel. Save it in Kaggle datasets. Upload the mantisshrimp code in datasets. 
In a new Inference, kernel Instantiate the model as you did while training. You need mantisshrimp codebase for that.  `load_state_dict()`  using torch to load the weights. And simply do the inference.

I am working to get the `.whl` file. As of now I am providing a zip of source code. Let me know if this works, I will provide wheel too.
[mantisshrimp-master.zip](https://github.com/lgvaz/mantisshrimp/files/4977519/mantisshrimp-master.zip)

**Comment by oke-aditya** [comment] 2020-07-26 11:55
- This has `.whl` and `.tar.gz`
[dist.zip](https://github.com/lgvaz/mantisshrimp/files/4977532/dist.zip)

**Comment by rashmimarganiatgithub** [comment] 2020-07-26 12:00
yes, I already have a reference to that above-mentioned kernel. And already tried with mantisshrimp-master.zip file while creating inference kernel. However, Kaggle kernel supports only binarized code in offline for now.
here is the part of code from the inference code for training file. 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sys
#!cp -r ../input/mantis/mantisshrimp-master/* .
sys.path.insert(0, "../input/mantis/mantisshrimp-master")


Here is the error

#from mantisshrimp.imports import *
from mantisshrimp import *
import pandas as pd
import albumentations as A

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-dfdaa6985263> in <module>
      1 #from mantisshrimp.imports import *
----> 2 from mantisshrimp import *
      3 import pandas as pd
      4 import albumentations as A

/kaggle/input/mantis/mantisshrimp-master/mantisshrimp/__init__.py in <module>
----> 1 from mantisshrimp.utils import *
      2 from mantisshrimp.core import *
      3 from mantisshrimp.parsers import *
      4 from mantisshrimp.data import *
      5 from mantisshrimp.transforms import *

/kaggle/input/mantis/mantisshrimp-master/mantisshrimp/utils/__init__.py in <module>
----> 1 from mantisshrimp.utils.utils import *
      2 from mantisshrimp.utils.torch_utils import *
      3 from mantisshrimp.utils.imageio import *
      4 from mantisshrimp.utils.get_files import *
      5 from mantisshrimp.utils.download_utils import *

/kaggle/input/mantis/mantisshrimp-master/mantisshrimp/utils/utils.py in <module>
     17 ]
     18 
---> 19 from mantisshrimp.imports import *
     20 
     21 

/kaggle/input/mantis/mantisshrimp-master/mantisshrimp/imports.py in <module>
      1 import cv2, json, torch, torchvision, dataclasses, zipfile
      2 
----> 3 from fastcore.imports import *
      4 from fastcore.foundation import *
      5 from fastcore.utils import *

ModuleNotFoundError: No module named 'fastcore'

**Comment by rashmimarganiatgithub** [comment] 2020-07-26 12:01
> * This has `.whl` and `.tar.gz`
>   [dist.zip](https://github.com/lgvaz/mantisshrimp/files/4977532/dist.zip)

thanks much.

**Comment by rashmimarganiatgithub** [comment] 2020-07-26 13:43
@oke-aditya  , code is breaking after installing the package here is the error

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-23-6ee8eaa61a42> in <module>
----> 1 from mantisshrimp.models.rcnn.faster_rcnn import *
      2 from mantisshrimp.models.rcnn import *

/opt/conda/lib/python3.7/site-packages/mantisshrimp/__init__.py in <module>
----> 1 from mantisshrimp.utils import *
      2 from mantisshrimp.core import *
      3 from mantisshrimp.parsers import *
      4 from mantisshrimp.data import *
      5 from mantisshrimp.transforms import *

/opt/conda/lib/python3.7/site-packages/mantisshrimp/utils/__init__.py in <module>
      5 from mantisshrimp.utils.download_utils import *
      6 from mantisshrimp.utils.data_dir import *
----> 7 from mantisshrimp.utils.soft_dependencies import *
      8 from mantisshrimp.utils.capture_stdout import *

/opt/conda/lib/python3.7/site-packages/mantisshrimp/utils/soft_dependencies.py in <module>
      2 
      3 try:
----> 4     import fastai2.vision.all as fastai
      5 
      6     HAS_FASTAI = True

/opt/conda/lib/python3.7/site-packages/fastai2/vision/all.py in <module>
----> 1 from ..basics import *
      2 from ..callback.all import *
      3 from .augment import *
      4 from .core import *
      5 from .data import *

/opt/conda/lib/python3.7/site-packages/fastai2/basics.py in <module>
----> 1 from .data.all import *
      2 from .optimizer import *
      3 from .callback.core import *
      4 from .learner import *
      5 from .metrics import *

/opt/conda/lib/python3.7/site-packages/fastai2/data/all.py in <module>
----> 1 from ..torch_basics import *
      2 from .core import *
      3 from .load import *
      4 from .external import *
      5 from .transforms import *

/opt/conda/lib/python3.7/site-packages/fastai2/torch_basics.py in <module>
      3 from .torch_imports import *
      4 from .torch_core import *
----> 5 from .layers import *

/opt/conda/lib/python3.7/site-packages/fastai2/layers.py in <module>
    271 
    272 # Cell
--> 273 @log_args
    274 class BaseLoss():
    275     "Same as `loss_cls`, but flattens input and target."

NameError: name 'log_args' is not defined

**Comment by oke-aditya** [comment] 2020-07-26 14:00
@rashmimarganiatgithub have a look at #222. Let us fix it there. I have commented on one of the solutions and why it isn't working as of now.

**Comment by lgvaz** [comment] 2020-07-26 14:32
@rashmimarganiatgithub Can you provide us with a reproducer for the error?

I do not currently understand why you're getting that error, you can maybe provide us with a colab/kaggle notebook that gives the error and then we try to fix it.

**Comment by lgvaz** [comment] 2020-07-26 15:00
This is now being tracked at #222

**Closed by lgvaz** 2020-07-26 15:00 UTC
Labels: bug
