### ISSUE TITLE
UnicodeDecodeError when installing

### ISSUE THREAD

**Issue by tazu786** [lgvaz/mantisshrimp#93] opened 2020-06-18 11:55 UTC
## 🐛 Bug
**Describe the bug**
Error when I install through pip.

**To Reproduce**
1. run `pip install git+git://github.com/lgvaz/mantisshrimp.git`

>... 
"c:\users\...\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 554: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Expected behavior**
Installation

**Desktop (please complete the following information):**
 - OS: [win 10]

**Additional context**

**Comment by oke-aditya** [comment] 2020-06-18 12:04
Thank you for the bug report. I am too able to reproduce the bug. 

OS windows 10 pro 64bit
Python version 3.6

```
PS C:\Users\hp> pip uninstall manstisshrimp
WARNING: Skipping manstisshrimp as it is not installed.
PS C:\Users\hp> pip install git+git://github.com/lgvaz/mantisshrimp.git
Collecting git+git://github.com/lgvaz/mantisshrimp.git
  Cloning git://github.com/lgvaz/mantisshrimp.git to c:\users\hp\appdata\local\temp\pip-req-build-piohh5yv
  Running command git clone -q git://github.com/lgvaz/mantisshrimp.git 'C:\Users\hp\AppData\Local\Temp\pip-req-build-piohh5yv'
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-req-build-piohh5yv\\setup.py'"'"'; __file__='"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-req-build-piohh5yv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\hp\AppData\Local\Temp\pip-pip-egg-info-s1vdaybl'
         cwd: C:\Users\hp\AppData\Local\Temp\pip-req-build-piohh5yv\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hp\AppData\Local\Temp\pip-req-build-piohh5yv\setup.py", line 63, in <module>
        long_description=open("README.rst").read(),
      File "c:\program files\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 554: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
PS C:\Users\hp>
PS C:\Users\hp>
```

**Comment by oke-aditya** [comment] 2020-06-18 12:08
Thank you @tazu786 
The library works fine on Linux systems. It installed on Google Colab which is Ubuntu 18.04 system.
https://colab.research.google.com/drive/13bWiJKT-jitZCJAhOPusHcXaq8pz3Bsc?usp=sharing

This is OS-specific issue. It will be fixed soon. Sorry for inconvenience. For now, you may use Google Colab and it should work fine.

**Comment by tazu786** [comment] 2020-06-18 13:18
Thank you @oke-aditya 
I managed to install it just with `pip install mantisshrimp`. Most of the imports work fine except for
`from mantisshrimp.hub.detr import *`
for which I get
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mantisshrimp.hub'

**Comment by oke-aditya** [comment] 2020-06-18 13:56
It is working on colab @tazu786 . I will check on windows. The package is not realeased on PyPi so pip install might not work.

**Comment by tazu786** [comment] 2020-06-18 14:39
Thank you @oke-aditya , I installed manually and it works.

**Comment by lgvaz** [comment] 2020-06-18 16:43
Hello @tazu786 , thanks for reaching out

Did you managed to fix the error at the end?

**Comment by lgvaz** [comment] 2020-06-18 17:00
I'll check the issue and get back to you asap 😄

**Comment by lgvaz** [comment] 2020-06-18 18:08
@oke-aditya is this the error related to pycocotools you were talking about?

I updated the install instructions and successfully installed on macOS. Can you still reproduce the error on windows?

**Comment by oke-aditya** [comment] 2020-06-18 18:12
Yes still error is prevailing 
![image](https://user-images.githubusercontent.com/47158509/85056767-6df61300-b1bd-11ea-894e-87d762c4ec00.png)

**Comment by oke-aditya** [comment] 2020-06-18 18:19
Yes still error is prevailing. I will fix it up.

**Comment by lgvaz** [comment] 2020-06-18 18:26
Meanwhile @tazu786 , I added a new example to [colab](https://colab.research.google.com/github/lgvaz/mantisshrimp/blob/master/tutorials/hub_detr_finetune_pennfundan.ipynb), everything is working no additional setup required

be sure to check it out 😁

**Comment by oke-aditya** [comment] 2020-06-18 18:38
PR opened for this. #95

**Comment by oke-aditya** [comment] 2020-06-18 18:49
The problem is not with pycoco tools thats another issue. It isn't our problem pycoco tools do not support windows.
It was simple file encoding utf-8 which linux assumes by defualt and hence CI / Colab / MacOS built it easily.

**Comment by oke-aditya** [comment] 2020-06-18 20:01
Can you try again from the orignal method suggested in readme. Setup.py should work now.

**Comment by tazu786** [comment] 2020-06-19 07:55
both the installation and the new colab work fine! Thank you both! @oke-aditya @lgvaz

**Closed** 2020-06-19 13:40 UTC
Labels: bug
